//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DAL.MsSql.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connector
    {
        public string Id { get; set; }
        public bool Disabled { get; set; }
        public Nullable<System.DateTime> LastCheckDate { get; set; }
    }
}
