//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DAL.MsSql.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbLogEntry
    {
        public int Id { get; set; }
        public int Severity { get; set; }
        public System.DateTime Time { get; set; }
        public string Message { get; set; }
        public string Details { get; set; }
    }
}
