//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DAL.MsSql.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbAdHistoryItem
    {
        public int Id { get; set; }
        public int AdId { get; set; }
        public double Price { get; set; }
        public System.DateTime AdCollectDate { get; set; }
        public System.DateTime AdPublishDate { get; set; }
    
        public virtual DbAd Ad { get; set; }
    }
}
