//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DAL.MsSql.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbAdsRealty : DbAd
    {
        public string Address { get; set; }
        public int RoomsCount { get; set; }
        public int Floor { get; set; }
        public int FloorsCount { get; set; }
        public double LivingSpace { get; set; }
        public bool IsNewBuilding { get; set; }
        public double PricePerMeter { get; set; }
    }
}
