//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DAL.MsSql.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdCollectorDBEntities : DbContext
    {
        public AdCollectorDBEntities()
            : base("name=AdCollectorDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DbAdLink> AdLinks { get; set; }
        public DbSet<DbAd> Ads { get; set; }
        public DbSet<DbLogEntry> LogEntries { get; set; }
        public DbSet<DbSetting> Settings { get; set; }
        public DbSet<DbAdHistoryItem> DbAdHistoryItems { get; set; }
        public DbSet<DbMetadata> DbMetadatas { get; set; }
        public DbSet<DbAdImage> DbAdImages { get; set; }
        public DbSet<DbStreet> DbStreets { get; set; }
        public DbSet<DbConnector> DbConnectors { get; set; }
        public DbSet<DbTag> DbTags { get; set; }
        public DbSet<DbUserProfile> DbUserProfiles { get; set; }
    }
}
